onlyOneBackUp: 1
indentPreamble: 1
verbatimEnvironments:
    cmhlistings: 1
    yaml: 1
    commandshell: 1
    lstlisting: 1
indentAfterHeadings:
    section:
       indentAfterThisHeading: 1
       level: 1
    subsection:
       indentAfterThisHeading: 1
       level: 1
    yamltitle:
       indentAfterThisHeading: 1
       level: 1
    flagbox:
       indentAfterThisHeading: 1
       level: 1
    subsubsection:
       indentAfterThisHeading: 1
       level: 1
